name: Deno Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Install dependencies
        run: deno cache --reload --unstable deps.ts

      - name: Copy config.json
        run: cp config.sample.json config.json

      - name: Run tests
        run: deno test -A
